apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rke2-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/001123/lab-harvester-gitops.git
    targetRevision: main
    path: gitops/infrastructure/rke2-cluster
    helm:
      valuesObject:
        harvesterClusterId: "c-gsrxm"
        cloudCredentialSecretName: "cc-gxmg8"
        kubernetesVersion: "v1.36.4+rke2r1"
  destination:
    name: rancher-server
    namespace: fleet-default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
