apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ksops-secret.yaml

resources:
  - 00-image.yaml
  - 03-vm.yaml
  - 05-harvester-agent-healer.yaml
  - 05a-capi-crd-fix-job.yaml
