apiVersion: rke-machine-config.cattle.io/v1
kind: HarvesterConfig
metadata:
  name: "{{ .Values.clusterName }}-cp-config"
  namespace: "{{ .Values.namespace }}"
clusterId: {{ .Values.harvesterClusterId | quote }}
clusterType: imported
vmNamespace: default
cpuCount: {{ .Values.controlPlane.cpuCount | quote }}
memorySize: {{ .Values.controlPlane.memorySize | quote }}
diskSize: {{ .Values.controlPlane.diskSize | quote }}
imageName: {{ .Values.imageName | quote }}
networkName: {{ .Values.networkName | quote }}
networkModel: virtio
sshUser: {{ .Values.sshUser | quote }}
userData: I2Nsb3VkLWNvbmZpZwp1c2VyczoKICAtIGRlZmF1bHQKICAtIG5hbWU6IG9wZW5zdXNlCiAgICBncm91cHM6IFt3aGVlbCwgc3Vkb10KICAgIHN1ZG86IFsiQUxMPShBTEwpIE5PUEFTU1dEOkFMTCJdCiAgICBzaGVsbDogL2Jpbi9iYXNoCnJ1bmNtZDoKICAtIFtzeXN0ZW1jdGwsIGVuYWJsZSwgLS1ub3csIHFlbXUtZ3Vlc3QtYWdlbnRdCiAgLSBbJ3NoJywgJy1jJywgJ2VjaG8gIjE5Mi4xNjguMjUwLjIgcmFuY2hlci4xOTIuMTY4LjI1MC4yLnNzbGlwLmlvIiA+PiAvZXRjL2hvc3RzJ10K
---
apiVersion: rke-machine-config.cattle.io/v1
kind: HarvesterConfig
metadata:
  name: "{{ .Values.clusterName }}-wk-config"
  namespace: "{{ .Values.namespace }}"
clusterId: {{ .Values.harvesterClusterId | quote }}
clusterType: imported
vmNamespace: default
cpuCount: {{ .Values.workers.cpuCount | quote }}
memorySize: {{ .Values.workers.memorySize | quote }}
diskSize: {{ .Values.workers.diskSize | quote }}
imageName: {{ .Values.imageName | quote }}
networkName: {{ .Values.networkName | quote }}
networkModel: virtio
sshUser: {{ .Values.sshUser | quote }}
userData: I2Nsb3VkLWNvbmZpZwp1c2VyczoKICAtIGRlZmF1bHQKICAtIG5hbWU6IG9wZW5zdXNlCiAgICBncm91cHM6IFt3aGVlbCwgc3Vkb10KICAgIHN1ZG86IFsiQUxMPShBTEwpIE5PUEFTU1dEOkFMTCJdCiAgICBzaGVsbDogL2Jpbi9iYXNoCnJ1bmNtZDoKICAtIFtzeXN0ZW1jdGwsIGVuYWJsZSwgLS1ub3csIHFlbXUtZ3Vlc3QtYWdlbnRdCiAgLSBbJ3NoJywgJy1jJywgJ2VjaG8gIjE5Mi4xNjguMjUwLjIgcmFuY2hlci4xOTIuMTY4LjI1MC4yLnNzbGlwLmlvIiA+PiAvZXRjL2hvc3RzJ10K
