apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
spec:
  cloudCredentialSecretName: cattle-global-data:{{ .Values.cloudCredentialSecretName }}
  kubernetesVersion: {{ .Values.kubernetesVersion }}
  rkeConfig:
    machinePools:
    - name: cp
      quantity: {{ .Values.controlPlane.quantity }}
      controlPlaneRole: true
      etcdRole: true
      workerRole: false
      machineConfigRef:
        apiVersion: rke-machine-config.cattle.io/v1
        kind: HarvesterConfig
        name: {{ .Values.clusterName }}-cp-config
    - name: wk
      quantity: {{ .Values.workers.quantity }}
      controlPlaneRole: false
      etcdRole: false
      workerRole: true
      machineConfigRef:
        apiVersion: rke-machine-config.cattle.io/v1
        kind: HarvesterConfig
        name: {{ .Values.clusterName }}-wk-config
