apiVersion: v1
kind: Secret
metadata:
    name: demo-secret
    namespace: demo-app
type: Opaque
stringData:
    API_TOKEN: ENC[AES256_GCM,data:XgnqIm3c71Ycx//8IYOwX3EzaofDoZCj9FdxXa9AqyzJp/iVqA==,iv:Yr7f/DRt9BVtkMMZTV0Kz06GMXg7ovM7h2yWtwFzje0=,tag:G25EhhTtIyshSAYysa9HSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZlNBUmFHNFE3OUlWZVQr
            NUF0ZS9mVy9FSUpjM05wbVlWVENLY3pYbURFCmpkbmZ4Mml5RzRtL3hoVGs0RW1L
            V2lVdFRnUW5IY3MvZnRNWGpNZmgxQncKLS0tIHNjKzhDaE55alpLc0RnUWY1c1hr
            ZFBReStPbDREc2ttVDNvVjZMZklrTGMKJ8hEkI05mKMCBGVbGqR498VFI0EVKPc0
            Iin2tSoReAT1wyG3Kv+89S6PizqjPMyih5gD/z3lnZI0Ryz8yJ2zRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13hphavvlee240rq0j42j60mqxj8s4k9tp473g076xl5z35p8mgjqx29stw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T12:34:02Z"
    mac: ENC[AES256_GCM,data:8DtUVAzhvc0KZ2NyHHrPOXCwwDscu/yfrec4UN265GN/O6PMGYh29/s4lXMDgYyPWo5koZyaYI9dQTUWatJImhiItZinuXb59NtkAiG0IDoAGs4w3Gy8OCSzRYL/yniXucJq70HFRFAG9TBpfW445bOUettY06ktMdoaNnOB7YQ=,iv:Uc24XUjlMWe0/mrYsi+NrasS5n5ixY4tTg+4V71uM94=,tag:+SPnfNW9ImrhbqEKZhAUEg==,type:str]
    version: 3.13.3
