apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-cd
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: argocd
  storageNamespace: argocd
  kubeConfig:
    secretRef:
      name: rke2-kubeconfig
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: argo-cd
      version: "10.8.4"
      sourceRef:
        kind: HelmRepository
        name: argo-helm
        namespace: flux-system
  values:
    global:
      domain: argocd.192.168.250.165.sslip.io
    server:
      insecure: true
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: argocd.192.168.250.165.sslip.io
        paths:
          - /
        pathType: Prefix
        extraHosts:
          - name: argocd.192.168.250.223.sslip.io
            path: /
            pathType: Prefix
    configs:
      cm:
        kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
        timeout.reconciliation: 180s
      params:
        server.insecure: true
    repoServer:
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age
            optional: true
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
        - mountPath: /home/argocd/.config/sops/age
          name: sops-age
      env:
        - name: XDG_CONFIG_HOME
          value: /custom-tools
        - name: SOPS_AGE_KEY_FILE
          value: /home/argocd/.config/sops/age/age.agekey
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.4.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Installing KSOPS..."
              cp /usr/local/bin/ksops /custom-tools/ksops
              mkdir -p /custom-tools/kustomize/plugin/viaduct.ai/v1alpha1/ksops
              cp /usr/local/bin/ksops /custom-tools/kustomize/plugin/viaduct.ai/v1alpha1/ksops/ksops
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
