apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: rke2-lab
  namespace: fleet-default
spec:
  cloudCredentialSecretName: cattle-global-data:cc-tb5bm
  kubernetesVersion: v1.36.4+rke2r1
  rkeConfig:
    machinePools:
    - name: cp
      quantity: 1
      controlPlaneRole: true
      etcdRole: true
      workerRole: false
      machineConfigRef:
        apiVersion: rke-machine-config.cattle.io/v1
        kind: HarvesterConfig
        name: rke2-cp-config
    - name: wk
      quantity: 2
      controlPlaneRole: false
      etcdRole: false
      workerRole: true
      machineConfigRef:
        apiVersion: rke-machine-config.cattle.io/v1
        kind: HarvesterConfig
        name: rke2-wk-config
