apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-nextjs-16
  namespace: demo-nextjs-16
  labels:
    app.kubernetes.io/name: demo-nextjs-16
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - nextjs.192.168.250.99.sslip.io
      secretName: demo-nextjs-16-tls
  rules:
    - host: nextjs.192.168.250.99.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-nextjs-16
                port:
                  number: 80

