apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
  sync:
    kind: GitRepository
    url: "https://github.com/001123/lab-harvester-gitops.git"
    ref: "refs/heads/main"
    path: "./gitops/clusters/harvester"
    interval: 1m
